services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.4.5
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.anantagarwal.me
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`pi.local`) || Host(`homepage.anantagarwal.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  default:
    name: homelab-network
    external: true