services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.4.5
    container_name: homepage
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "homepage.anantagarwal.me,192.168.1.55:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`pi.local`) || Host(`homepage.anantagarwal.me`)"
      - "traefik.http.routers.homepage.entrypoints=web"

networks:
  default:
    name: homelab-network
    external: true