services:  
  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: always

networks:
  default:
    name: homelab-network
    external: true